#!/usr/bin/env bash

bold=$(tput bold)
normal=$(tput sgr0)

uzn_file=$1

if [[ ! -f $uzn_file ]]
then
  echo "Cannot find uzn file $uzn_file, exiting" 1>&2
  exit 1
fi

if [[ ${uzn_file##*.} == "uzn" ]]
then
  :
else
  echo "First parameter must be .uzn file, exiting" 1>&2
  exit 1
fi

for image_file in "${@:2}" ; do

  if [[ ! -f "$image_file" ]]
  then
    echo "Cannot find image file $image_file, exiting" 1>&2
    exit 1
  fi

  echo "${bold}Processing image file $image_file${normal}"

  tmpdir=`mktemp -d 2>/dev/null || mktemp -d -t 'mytmpdir'`

  directory="$(dirname "$image_file")"
  filename="$(basename "$image_file")"
  extension="${image_file##*.}"

  uzn_tmp="$tmpdir/$filename.uzn"
  image_tmp="$tmpdir/$filename.$extension"
  txt_target="$directory/$filename"

  echo "Copying to temporary directory ${bold}$tmpdir${normal}"

  cp "$uzn_file" "$uzn_tmp"
  cp "$image_file" "$image_tmp"

  echo "Saving output to ${bold}$txt_target.txt${normal}"

  if ! tesseract "$image_tmp" "$txt_target" -psm 4
  then
    echo "Can't find the tesseract executable, make sure it's in your PATH" 1>&2
    exit 1
  fi
  echo ""
done

echo "${bold}Done.${normal}"